usingConfig: true
config-version: 1

tabmenu:
  enabled: true
  header: '&3MyServer'
  footer: '&bIP: play.myserver.com'
welcome_message:
  enabled: true
  title: '&5Welcome {PLAYER}'
  subtitle: '&dTo sweggy mc sweg!'
  fadeIn: -1
  stay: -1
  fadeOut: -1
return_message:
  enabled: true
  title: '&5Welcome back, {PLAYER}'
  subtitle: '&dTo sweggy mc sweg!'
  fadeIn: -1
  stay: -1
  fadeOut: -1
