name: TitleManager
version: 1.3.1
author: Puharesource

main: io.puharesource.mc.titlemanager.Main
softdepend: [Vault]

commands:
  tm:
    description: TitleManager commands.
    usage: /tm
    aliases: [titlemanager]