name: TitleManagerReborn
version: 1.0.0
author: MinekartaStudio
api-version: 1.13

main: studio.minekarta.titlemanagerreborn.TitleManagerReborn
softdepend: [Vault, Essentials, VanishNoPacket, PlaceholderAPI, SuperVanish, PremiumVanish, MVdWPlaceholderAPI, CombatLogX]

commands:
  tm:
    description: TitleManager commands.
    usage: /tm
    aliases: [titlemanager]
